In [2]:
import numpy as np 
arr=np.array([23,45,56])
print(arr*2)

[ 46  90 112]


In [4]:
import numpy as np 
arr=np.array([34,56,78])
result=arr*2
print(result)


[ 68 112 156]


In [8]:
#it can be also two dimenson
arr=np.array([[1,2,3],
             [4,5,6]
])

arr.shape
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [9]:
numbers = [1, 2, 3]

print(numbers * 2)

[1, 2, 3, 1, 2, 3]


In [10]:
import numpy as np

numbers = np.array([1, 2, 3])

print(numbers * 2)

[2 4 6]


In [11]:
import numpy as np

arr = np.array([1, 2, 3])

print(arr.dtype)

int32


In [14]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr.shape
arr.size
arr.ndim

2

In [26]:
arr2=np.array([1,2,3,4,5,6,7,8,9])
new=arr2.reshape(3,3)
new

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])