In [7]:
import numpy as np
arr=np.array([
    [1,2,3],
     [4,5,6]
])

In [8]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [9]:
new = arr.ravel()

In [10]:
new

array([1, 2, 3, 4, 5, 6])

In [11]:
import numpy as np 
arr=np.array([
    [1,2,3],
    [5,6,7]
])

In [12]:
arr+10

array([[11, 12, 13],
       [15, 16, 17]])

In [13]:
b=np.array([10,23,45])
print(arr+b)

[[11 25 48]
 [15 29 52]]
